import { createPagesFunctionHandler } from "@react-router/cloudflare";
import type { ServerBuild } from "react-router";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore - the server build file is generated by `react-router build`
import * as build from "../build/server";

// The build is emitted JavaScript, so TypeScript infers widened literal types
// for route module exports (e.g. `crossOrigin: string`). The shape is correct
// at runtime; assert it rather than weakening the route modules' own types.
export const onRequest = createPagesFunctionHandler({
  build: build as unknown as ServerBuild,
});
