// Generated by Wrangler
// After adding bindings to `wrangler.toml`, regenerate this interface via `npm run cf-typegen`
interface Env {
  RESEND_API_KEY: any;
  SUPABASE_ANON_KEY: any;
  SUPABASE_URL: any;
}
